<?php require_once __DIR__.'/comman/auth.php'; $pageTitle='Dashboard'; require __DIR__.'/comman/header.php'; require __DIR__.'/comman/sidebar.php';
$games=read_json(SITE_ROOT.'/data/games.json',[]); $posts=admin_data('posts.json',[]); $promos=admin_data('promo_codes.json',[]); $cats=admin_data('categories.json',[]);
$activeGames=count(array_filter($games,fn($g)=>!isset($g['status'])||!empty($g['status']))); $publishedPosts=count(array_filter($posts,fn($p)=>($p['status']??'published')!=='draft')); $activePromos=count(array_filter($promos,fn($p)=>!isset($p['active'])||!empty($p['active'])));
$recentGames=array_slice(array_reverse($games),0,6); $recentPosts=array_slice(array_reverse($posts),0,6); $today=date('d M Y');
?>
<div class="content-wrapper"><section class="content-header"><div class="container-fluid"><div class="row align-items-end"><div class="col-md-8"><div class="yl-breadcrumb">CONTROL CENTER / OVERVIEW</div><h1 class="yl-page-title">Good to see you, Admin 👋</h1><div class="yl-page-sub">Manage games, publish daily updates, control your homepage and grow YonoLootZone from one place.</div></div><div class="col-md-4 text-md-right yl-header-actions"><a href="../index.html" target="_blank" class="btn btn-light border mr-1"><i class="fas fa-external-link-alt mr-1"></i> View Site</a><a href="posts.php" class="btn btn-pink"><i class="fas fa-plus mr-1"></i> New Post</a></div></div><?php if($flash):?><div class="alert alert-<?=h($flash[0])?> mt-3 mb-0"><?=h($flash[1])?></div><?php endif;?></div></section>
<section class="content"><div class="container-fluid">
<div class="yl-hero"><i class="fas fa-bolt yl-hero-icon"></i><div class="yl-hero-meta"><h2>Your publishing command center</h2><p>Today is <?=h($today)?>. Keep your content fresh, connect every update to the right game page, and monitor the core website controls here.</p><div class="yl-hero-actions"><a href="add_game.php" class="btn btn-pink"><i class="fas fa-gamepad mr-1"></i> Add New Game</a><a href="promo_codes.php" class="btn btn-dark"><i class="fas fa-ticket-alt mr-1"></i> Add Promo Code</a><a href="homepage.php" class="btn btn-outline-light"><i class="fas fa-sliders-h mr-1"></i> Customize</a></div></div></div>
<div class="row"><div class="col-xl-3 col-md-6"><div class="card yl-kpi"><div class="card-body"><div class="yl-kpi-top"><span class="yl-kpi-icon yl-pink"><i class="fas fa-gamepad"></i></span><i class="fas fa-ellipsis-h text-muted"></i></div><div class="yl-kpi-number"><?=count($games)?></div><div class="yl-kpi-label">TOTAL GAMES</div><div class="yl-kpi-foot"><span class="text-success font-weight-bold"><?= $activeGames ?></span> currently active</div></div></div></div>
<div class="col-xl-3 col-md-6"><div class="card yl-kpi"><div class="card-body"><div class="yl-kpi-top"><span class="yl-kpi-icon yl-blue"><i class="fas fa-file-alt"></i></span><i class="fas fa-ellipsis-h text-muted"></i></div><div class="yl-kpi-number"><?=count($posts)?></div><div class="yl-kpi-label">TOTAL POSTS</div><div class="yl-kpi-foot"><span class="text-primary font-weight-bold"><?=$publishedPosts?></span> published</div></div></div></div>
<div class="col-xl-3 col-md-6"><div class="card yl-kpi"><div class="card-body"><div class="yl-kpi-top"><span class="yl-kpi-icon yl-orange"><i class="fas fa-ticket-alt"></i></span><i class="fas fa-ellipsis-h text-muted"></i></div><div class="yl-kpi-number"><?=count($promos)?></div><div class="yl-kpi-label">PROMO CODES</div><div class="yl-kpi-foot"><span class="text-warning font-weight-bold"><?=$activePromos?></span> active</div></div></div></div>
<div class="col-xl-3 col-md-6"><div class="card yl-kpi"><div class="card-body"><div class="yl-kpi-top"><span class="yl-kpi-icon yl-green"><i class="fas fa-layer-group"></i></span><i class="fas fa-ellipsis-h text-muted"></i></div><div class="yl-kpi-number"><?=count($cats)?></div><div class="yl-kpi-label">CATEGORIES</div><div class="yl-kpi-foot"><span class="text-success font-weight-bold">Ready</span> for publishing</div></div></div></div></div>
<div class="row mt-1"><div class="col-xl-8"><div class="card yl-card"><div class="card-header"><div class="d-flex justify-content-between align-items-center"><div><h3 class="yl-card-title">Recent Games</h3><div class="yl-card-sub">Your latest game entries and publishing status</div></div><a href="games.php" class="btn btn-sm btn-light border font-weight-bold">View all <i class="fas fa-arrow-right ml-1"></i></a></div></div><div class="card-body p-0"><div class="yl-scroll"><table class="table yl-table mb-0"><thead><tr><th>Game</th><th>Category</th><th>Status</th><th class="text-right">Action</th></tr></thead><tbody><?php if(!$recentGames):?><tr><td colspan="4" class="text-center text-muted py-5">No games yet.</td></tr><?php endif;?><?php foreach($recentGames as $g): $img=$g['image']??$g['image_url']??'';?><tr><td><div class="d-flex align-items-center"><img class="yl-thumb mr-2" src="<?=h($img)?>" onerror="this.style.display='none'"><div><strong><?=h($g['name']??'Untitled')?></strong><div class="text-muted" style="font-size:10px"><?=h($g['slug']??'')?></div></div></div></td><td><?=h($g['category']??'Uncategorized')?></td><td><span class="yl-status <?=(!isset($g['status'])||!empty($g['status']))?'active':'off'?>"><?=(!isset($g['status'])||!empty($g['status']))?'ACTIVE':'HIDDEN'?></span></td><td class="text-right"><a href="add_game.php?edit=<?=urlencode($g['slug']??'')?>" class="btn btn-sm btn-light border"><i class="fas fa-pen"></i></a></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="card yl-card mt-3"><div class="card-header"><div class="d-flex justify-content-between align-items-center"><div><h3 class="yl-card-title">Recent Posts</h3><div class="yl-card-sub">Latest content published through your CMS</div></div><a href="posts.php" class="btn btn-sm btn-light border font-weight-bold">Manage posts <i class="fas fa-arrow-right ml-1"></i></a></div></div><div class="card-body p-0"><div class="yl-scroll"><table class="table yl-table mb-0"><thead><tr><th>Title</th><th>Type</th><th>Status</th></tr></thead><tbody><?php if(!$recentPosts):?><tr><td colspan="3" class="text-center text-muted py-5">No posts yet. Publish your first update.</td></tr><?php endif;?><?php foreach($recentPosts as $p):?><tr><td><strong><?=h($p['title']??'Untitled Post')?></strong><div class="text-muted" style="font-size:10px"><?=h($p['slug']??'')?></div></td><td><?=h($p['type']??'Article')?></td><td><span class="yl-status active">PUBLISHED</span></td></tr><?php endforeach;?></tbody></table></div></div></div></div>
<div class="col-xl-4"><div class="card yl-card"><div class="card-header"><h3 class="yl-card-title">Quick Actions</h3><div class="yl-card-sub">Common publishing tasks</div></div><div class="card-body"><a class="yl-quick" href="posts.php"><span class="yl-quick-icon"><i class="fas fa-pen-nib"></i></span><span><strong>Publish daily update</strong><small>Create SEO-ready content</small></span><i class="fas fa-chevron-right arrow"></i></a><a class="yl-quick" href="add_game.php"><span class="yl-quick-icon"><i class="fas fa-gamepad"></i></span><span><strong>Add new game</strong><small>Build its game page</small></span><i class="fas fa-chevron-right arrow"></i></a><a class="yl-quick" href="promo_codes.php"><span class="yl-quick-icon"><i class="fas fa-ticket-alt"></i></span><span><strong>Add promo code</strong><small>Connect it to a game</small></span><i class="fas fa-chevron-right arrow"></i></a><a class="yl-quick" href="media.php"><span class="yl-quick-icon"><i class="fas fa-images"></i></span><span><strong>Upload media</strong><small>Images and videos</small></span><i class="fas fa-chevron-right arrow"></i></a></div></div>
<div class="card yl-card"><div class="card-header"><h3 class="yl-card-title">Website Health</h3><div class="yl-card-sub">Basic configuration checks</div></div><div class="card-body"><div class="yl-health-row"><span class="yl-health-label"><span class="yl-dot ok"></span>Website</span><span class="yl-health-value">Online</span></div><div class="yl-health-row"><span class="yl-health-label"><span class="yl-dot ok"></span>Game data</span><span class="yl-health-value"><?=count($games)?> records</span></div><div class="yl-health-row"><span class="yl-health-label"><span class="yl-dot ok"></span>Content system</span><span class="yl-health-value"><?=count($posts)?> posts</span></div><div class="yl-health-row"><span class="yl-health-label"><span class="yl-dot ok"></span>Promo system</span><span class="yl-health-value">Ready</span></div><div class="yl-health-row"><span class="yl-health-label"><span class="yl-dot ok"></span>Admin security</span><span class="yl-health-value">Protected</span></div></div></div>
<div class="card yl-card"><div class="card-header"><h3 class="yl-card-title">Need to change something?</h3></div><div class="card-body"><a href="seo.php" class="btn btn-outline-secondary btn-block font-weight-bold"><i class="fas fa-search mr-1"></i> SEO Center</a><a href="homepage.php" class="btn btn-outline-secondary btn-block font-weight-bold"><i class="fas fa-home mr-1"></i> Homepage Controls</a><a href="settings.php" class="btn btn-outline-secondary btn-block font-weight-bold mb-0"><i class="fas fa-cog mr-1"></i> System Settings</a></div></div></div></div>
</div></section></div><?php require __DIR__.'/comman/footer.php'; ?>
